### PR TITLE
Module split, added unittests, readme and Makefile

### PR DESCRIPTION
**Pull request by lunemec**
This should make the project a little bit easier to maintain.
The API itself hasn't changed and is backwards compatible.

### CODE REVIEW

**Comment by jzmiller1** [comment]
I'm a fan of this PR.

**Comment by n8felton** [comment]
:+1:

**Comment by ntt** [comment]
Eh. not a bad idea, but to be honest, I'm a little bit put off by people trying to change someone else's project's indent style.

**Comment by lunemec** [comment]
Oh, I'm sorry, I didn't notice you had tabs as indentation spacer. My editor automatically switches everything I save to 4 spaces per tab.... You could probably just open the files in your editor and replace it for \t ...

**Comment by a-tal** [comment]
I built on top of your PR @lunemec

https://github.com/a-tal/eveapi/tree/forked

switched from unittest to py.test + tox. implemented your caching thing for files and in memory (made memory default), couple other things here and there. py3 compat as well...

**Comment by lunemec** [comment]
Cool @a-tal I'll take a look when I have the time :)

**Comment by jonobrien** [comment]
any progress on this/similar?

**Pull request closed without merging**
